image: sublimino/alpine-base:latest

stages:
  - test
  - build
  - deploy
  - rollback

cache:
  untracked: true
  paths: 
  - /root/.npm
  - node_modules/


duplicate-remote:
  stage: test
  script:
    - env; git co $CI_BUILD_REF_NAME && git push --force https://sublimino-gitlab:$SUBLIMINO_BITBUCKET_PASS@bitbucket.org/sublimino/$(basename "$(pwd)").git

test:
  stage: test
  before_script:
    - node -v
    - npm install
  script: 
    - npm test

build:
  stage: build
  script:
    - ./rollcage.sh build

deploy:
  stage: deploy
  when:  on_success
  script:
    - echo DEPLOY

rollback:
  stage: rollback
  when: on_failure
  script:
    - echo rolling back
