image: sublimino/alpine-base:latest

stages:
  - test
  - build
  - deploy
  - rollback

cache:
  untracked: true
  paths: 
  - /root/.npm
  - node_modules/


duplicate-remote:
  stage: test
  script:
    - env; git checkout $CI_BUILD_REF_NAME && git push --verbose --atomic --prune https://sublimino-bot:$SUBLIMINO_BOT_PASS@github.com/sublimino/$(basename "$(pwd)").git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*

test-local:
  stage: test
  before_script:
    - node -v
    - npm install
  script: 
    - npm test

test-global:
  stage: test
  before_script:
    - node -v
    - npm install -g .
  script:
    - APP=rollcage npm test

build:
  stage: build
  script:
    - mkdir -p node_modules ; ./rollcage build && ./rollcage push

deploy:
  stage: deploy
  when:  on_success
  script:
    - echo DEPLOY

rollback:
  stage: rollback
  when: on_failure
  script:
    - echo rolling back
