image: sublimino/alpine-base:latest

stages:
  - test
  - build
  - deploy
  - rollback

cache:
  untracked: true
  paths: 
  - /root/.npm
  - node_modules/


duplicate-remote:
  stage: test
  script:
    - COMMAND="$(./rollcage git-backup)"; echo $COMMAND; $COMMAND;

test-local-install:
  stage: test
  before_script:
    - node -v
    - npm install
  script:
    - npm test

test-global-install:
  stage: test
  before_script:
    - node -v
    - npm install
    - npm install -g .
  script:
    - APP=rollcage npm test

build:
  stage: build
  script:
    - mkdir -p node_modules && ./rollcage build push

deploy:
  stage: deploy
  when:  on_success
  script:
    - echo DEPLOY

rollback:
  stage: rollback
  when: on_failure
  script:
    - echo rolling back
